// @ts-nocheck
/**
 * Mock Data for Development
 *
 * Realistic UK Police force data for testing the Focus Mode.
 */

import type { Lead, Signal, Contact, TalkingPoint } from "@/lib/types/lead";

/**
 * Mock Leads - Realistic police force data
 */
export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    organisationId: "org-met",
    organisationName: "Metropolitan Police Service",
    forceContext: {
      forceType: "territorial",
      forceSize: "large",
      officerCount: 34000,
      hmicfrsStatus: "engage",
      fiscalContext: "Q4 Budget Flush",
    },
    score: 92,
    scorePrev: 78,
    priority: "priority",
    scoreBreakdown: {
      signal: 85,
      signalPrev: 70,
      serviceFit: 95,
      serviceFitPrev: 95,
      relationship: 45,
      relationshipPrev: 40,
      timing: 75,
      timingPrev: 65,
    },
    signals: [
      {
        id: "sig-1",
        type: "hiring_surge",
        label: "Hiring Surge",
        points: 25,
        source: "Indeed",
        confidence: "A1",
        detectedAt: "2025-12-22T08:00:00Z",
        direction: "up",
      },
      {
        id: "sig-2",
        type: "signal_spike",
        label: "Signal Spike",
        points: 15,
        source: "Indeed",
        confidence: "B2",
        detectedAt: "2025-12-21T14:00:00Z",
        direction: "up",
      },
    ],
    primarySignal: {
      id: "sig-1",
      type: "hiring_surge",
      label: "Hiring Surge",
      points: 25,
      source: "Indeed",
      confidence: "A1",
      detectedAt: "2025-12-22T08:00:00Z",
      direction: "up",
    },
    leadType: "Hiring Signal - Investigation Services",
    triggerReason: "8 new investigator roles posted in 48 hours",
    recommendedAction: "Send introduction email",
    recommendedChannel: "email",
    timeSensitivity: "today",
    source: "Indeed job posting",
    contact: {
      id: "contact-1",
      name: "Sarah Mitchell",
      title: "Head of Professional Standards",
      email: "sarah.mitchell@met.police.uk",
      phone: "+44 20 7230 1212",
      linkedinUrl: "https://linkedin.com/in/sarahmitchell",
      confidence: "high",
      source: "HubSpot",
    },
    relationshipHistory: [
      {
        id: "event-1",
        type: "email",
        description: "Introduction email sent",
        date: "2025-11-15T10:00:00Z",
        outcome: "Opened, no reply",
      },
    ],
    draftMessage: {
      channel: "email",
      subject: "Supporting Met Police Investigation Capacity",
      body: `Hi {first_name},

I noticed the Met is recruiting several investigators at the moment. Given the current pressures on investigation capacity, I wanted to reach out.

Peel Solutions has helped {similar_force} reduce their investigation backlog by 40% through our specialist investigators who already hold {vetting_level} clearance.

Would you be open to a brief call this week to discuss how we might support your team?

Best regards,
James`,
      variables: [
        { name: "first_name", value: "Sarah", state: "resolved", placeholder: "[First Name]" },
        { name: "similar_force", value: "Surrey Police", state: "resolved", placeholder: "[Similar Force]" },
        { name: "vetting_level", value: "NPPV3", state: "resolved", placeholder: "[Vetting Level]" },
      ],
    },
    talkingPoints: [
      { id: "tp-1", label: "HMICFRS pressure", text: "Given the recent HMICFRS assessment..." },
      { id: "tp-2", label: "Surrey success", text: "We recently helped Surrey Police reduce..." },
    ],
    status: "new",
    createdAt: "2025-12-22T08:00:00Z",
    updatedAt: "2025-12-22T08:00:00Z",
    vettingLevel: "NPPV3",
    vettingBonus: 10,
  },
  {
    id: "lead-2",
    organisationId: "org-gmp",
    organisationName: "Greater Manchester Police",
    forceContext: {
      forceType: "territorial",
      forceSize: "large",
      officerCount: 8000,
      hmicfrsStatus: "ri",
    },
    score: 85,
    scorePrev: 82,
    priority: "high",
    scoreBreakdown: {
      signal: 75,
      signalPrev: 72,
      serviceFit: 90,
      serviceFitPrev: 90,
      relationship: 60,
      relationshipPrev: 55,
      timing: 70,
      timingPrev: 70,
    },
    signals: [
      {
        id: "sig-3",
        type: "followup_due",
        label: "Follow-up Due",
        points: 10,
        source: "CRM",
        confidence: "A1",
        detectedAt: "2025-12-22T07:00:00Z",
      },
      {
        id: "sig-4",
        type: "hiring_surge",
        label: "Hiring Surge",
        points: 20,
        source: "Indeed",
        confidence: "B2",
        detectedAt: "2025-12-20T09:00:00Z",
        direction: "up",
      },
    ],
    leadType: "Follow-up Required",
    triggerReason: "14-day follow-up window",
    recommendedAction: "Follow up on previous conversation",
    recommendedChannel: "email",
    timeSensitivity: "this_week",
    source: "CRM Follow-up",
    contact: {
      id: "contact-2",
      name: "David Chen",
      title: "Detective Chief Inspector",
      email: "david.chen@gmp.police.uk",
      confidence: "medium",
      source: "Enrichment",
    },
    relationshipHistory: [
      {
        id: "event-2",
        type: "call",
        description: "Discovery call - interested in Q1",
        date: "2025-12-08T14:00:00Z",
        outcome: "Positive - follow up in 2 weeks",
      },
    ],
    draftMessage: {
      channel: "email",
      subject: "Following up on our conversation",
      body: `Hi {first_name},

Following up on our conversation a couple of weeks ago about supporting GMP's investigation capacity.

Have you had a chance to discuss with your team? Happy to provide more details or set up a call with our operations team.

Best,
James`,
      variables: [
        { name: "first_name", value: "David", state: "resolved", placeholder: "[First Name]" },
      ],
    },
    talkingPoints: [],
    status: "reviewing",
    createdAt: "2025-12-08T14:00:00Z",
    updatedAt: "2025-12-22T07:00:00Z",
  },
  {
    id: "lead-3",
    organisationId: "org-titan",
    organisationName: "TITAN (North West ROCU)",
    forceContext: {
      forceType: "rocu",
      forceSize: "medium",
      officerCount: 500,
      hmicfrsStatus: "good",
    },
    score: 78,
    priority: "high",
    scoreBreakdown: {
      signal: 70,
      serviceFit: 85,
      relationship: 30,
      timing: 65,
    },
    signals: [
      {
        id: "sig-5",
        type: "hiring_surge",
        label: "Hiring Surge",
        points: 20,
        source: "Indeed",
        confidence: "B2",
        detectedAt: "2025-12-21T11:00:00Z",
        direction: "up",
      },
    ],
    leadType: "Hiring Signal - ROCU",
    triggerReason: "3 financial investigator roles posted",
    recommendedAction: "Send introduction email",
    recommendedChannel: "email",
    timeSensitivity: "this_week",
    source: "Indeed job posting",
    contact: {
      id: "contact-3",
      name: "Unknown",
      title: "Financial Investigation Unit",
      confidence: "low",
      source: "AI Discovery",
    },
    relationshipHistory: [],
    talkingPoints: [],
    status: "new",
    createdAt: "2025-12-21T11:00:00Z",
    updatedAt: "2025-12-21T11:00:00Z",
    vettingLevel: "SC",
    vettingBonus: 15,
  },
  {
    id: "lead-4",
    organisationId: "org-surrey",
    organisationName: "Surrey Police",
    forceContext: {
      forceType: "territorial",
      forceSize: "medium",
      officerCount: 2000,
      hmicfrsStatus: "good",
    },
    score: 72,
    priority: "medium",
    scoreBreakdown: {
      signal: 60,
      serviceFit: 80,
      relationship: 70,
      timing: 55,
    },
    signals: [
      {
        id: "sig-6",
        type: "re_engaged",
        label: "Re-engaged",
        points: 15,
        source: "HubSpot",
        confidence: "A1",
        detectedAt: "2025-12-20T16:00:00Z",
      },
    ],
    leadType: "Re-engagement",
    triggerReason: "Opened 3 emails in past week",
    recommendedAction: "Send check-in email",
    recommendedChannel: "email",
    timeSensitivity: "when_ready",
    source: "HubSpot Activity",
    contact: {
      id: "contact-4",
      name: "Emma Thompson",
      title: "Head of HR",
      email: "emma.thompson@surrey.police.uk",
      linkedinUrl: "https://linkedin.com/in/emmathompson",
      confidence: "high",
      source: "HubSpot",
    },
    relationshipHistory: [
      {
        id: "event-3",
        type: "meeting",
        description: "Initial pitch meeting",
        date: "2025-10-15T10:00:00Z",
        outcome: "Interested but budget frozen until April",
      },
    ],
    talkingPoints: [],
    status: "new",
    createdAt: "2025-12-20T16:00:00Z",
    updatedAt: "2025-12-20T16:00:00Z",
  },
  {
    id: "lead-5",
    organisationId: "org-btp",
    organisationName: "British Transport Police",
    forceContext: {
      forceType: "specialist",
      forceSize: "medium",
      officerCount: 3000,
      hmicfrsStatus: "outstanding",
    },
    score: 65,
    priority: "medium",
    scoreBreakdown: {
      signal: 55,
      serviceFit: 75,
      relationship: 40,
      timing: 50,
    },
    signals: [
      {
        id: "sig-7",
        type: "signal_spike",
        label: "Signal Spike",
        points: 10,
        source: "Indeed",
        confidence: "C3",
        detectedAt: "2025-12-19T09:00:00Z",
        direction: "neutral",
      },
    ],
    leadType: "Monitoring",
    triggerReason: "Unusual posting activity",
    recommendedAction: "Research and monitor",
    recommendedChannel: "linkedin",
    timeSensitivity: "when_ready",
    source: "Indeed job posting",
    contact: {
      id: "contact-5",
      name: "Unknown",
      confidence: "none",
      source: "N/A",
    },
    relationshipHistory: [],
    talkingPoints: [],
    status: "new",
    createdAt: "2025-12-19T09:00:00Z",
    updatedAt: "2025-12-19T09:00:00Z",
  },
  {
    id: "lead-6",
    organisationId: "org-nca",
    organisationName: "National Crime Agency",
    forceContext: {
      forceType: "national",
      forceSize: "large",
      officerCount: 5000,
    },
    score: 58,
    priority: "low",
    scoreBreakdown: {
      signal: 50,
      serviceFit: 70,
      relationship: 25,
      timing: 40,
    },
    signals: [
      {
        id: "sig-8",
        type: "competitor_activity",
        label: "Competitor Activity",
        points: 5,
        source: "Web",
        confidence: "D4",
        detectedAt: "2025-12-18T14:00:00Z",
        direction: "down",
      },
    ],
    leadType: "Competitor Intelligence",
    triggerReason: "Reed advertising NCA roles",
    recommendedAction: "Monitor",
    recommendedChannel: "email",
    timeSensitivity: "when_ready",
    source: "Competitor monitoring",
    status: "new",
    createdAt: "2025-12-18T14:00:00Z",
    updatedAt: "2025-12-18T14:00:00Z",
    relationshipHistory: [],
    talkingPoints: [],
  },
];

/**
 * Mock Session Stats
 */
export const mockSessionStats = {
  todayProcessed: 3,
  todayTotal: 12,
  allTimeProcessed: 147,
  averageTimeSeconds: 102, // 1:42
};
